### ISSUE TITLE
Error response from daemon: repository babble not found: does not exist or no pull access

### ISSUE THREAD

**Issue by buhrmi** [daragao/babble_example#1]
Hello,

thank you so much for putting up this example. I'm trying to run it, but I get the following error when running `sudo ./run-testnet-server`.

    Unable to find image 'babble:latest' locally
    Error response from daemon: repository babble not found: does not exist or no pull access

Any advice?

**Comment by buhrmi** [comment]
Okay, I forgot to run `babble/docker/make` to actually build the docker image (I'm new to docker, sorry). Now I get
    
    94af2b6db132f01052dbfaaedd54c11cdfed640715f9396c0d85233052198648
    + docker cp /home/buhrmi/babble_example/../node1 node1:/.babble
    lstat /home/buhrmi/node1: no such file or directory

**Comment by daragao** [comment]
Cool ;)
